In [1]:
import mysql.connector 

mydb = mysql.connector.connect(
    host="localhost",
    user="root",
    password=""
)

print(mydb)

In [5]:
pip install mysql-connector-python

Note: you may need to restart the kernel to use updated packages.


In [2]:
import mysql.connector

mydb = mysql.connector.connect(
    host="localhost",
    user="root",
    password=""
)

mycursor = mydb.cursor()

mycursor.execute("CREATE DATABASE Matutino")

In [3]:
import mysql.connector

mydb = mysql.connector.connect(
    host="localhost",
    user="root",
    password=""
)

mycursor = mydb.cursor()

mycursor.execute("SHOW DATABASES")

for x in mycursor:
    print(x)

('adventureworks',)
('album',)
('app_web_2_p1_cine',)
('app_web_2_p2_examen',)
('app_web_2_p2_permisos',)
('barberia_don_juan',)
('bd_peliculas',)
('bdd2-d1_biblioteca',)
('bdd2_pf_biblioteca',)
('blog',)
('bookingdb',)
('calidad_p2_t7_control_actividades',)
('customers',)
('db2_p2_t1_renta_peliculas',)
('db2_p3_t1_company',)
('db2_p3_t1_escolastico',)
('db2_p3_t1_usuarios',)
('db_example',)
('db_itsqmet_burger',)
('db_matt',)
('factu_pim',)
('hibernate_relationships',)
('hibernatetests',)
('information_schema',)
('l1_ejercicio_reservas',)
('login',)
('matutino',)
('mydatabase',)
('mysql',)
('northwind',)
('orders_management_crud',)
('performance_schema',)
('poo2_ep1_db_rrhh',)
('poo2_p2_t2_agenda',)
('poo2_tc3_grades',)
('rithv2_white',)
('school',)
('site',)
('sys',)
('t1_ventas',)
('tasksdb',)
('two_kash_app',)
('ventas2',)
('web_p3_t2_wordpress',)
('wp_melian_tienda',)
('wp_republica_deportes',)


In [4]:
import numpy as np
a = np.random.randint(10, size=(3,3))
np.save('arr', a)
a2 = np.load('arr.npy')
print(a2)

[[3 1 3]
 [3 9 4]
 [2 2 3]]
